### ISSUE TITLE
Class 'DOMDocument' not found in symfony/dom-crawler/Crawler.php:192

### ISSUE THREAD

**Issue by 33mhz** [dusterio/link-preview#3]
Will try to look up what's happening in the next few days, but I did a composer update and now I get this:

```
Fatal error: Uncaught Error: Class 'DOMDocument' not found in vendor/symfony/dom-crawler/Crawler.php:192
Stack trace:
#0 vendor/symfony/dom-crawler/Crawler.php(170): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 vendor/symfony/dom-crawler/Crawler.php(121): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 vendor/symfony/dom-crawler/Crawler.php(70): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 vendor/dusterio/link-preview/src/Parsers/HtmlParser.php(132): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 vendor/dusterio/link-preview/src/Parsers/HtmlParser.php(100): Dusterio\LinkPreview\Parsers\HtmlParser->parseHtml(Object(Dusterio                                            \LinkPreview\Models\Link))
#5 vendor/dusterio/link-preview/src/Client.php(61):
Dusteri in vendor/symfony/dom-crawler/Crawler.php on line 192
```

Not sure why it says "Dusteri" that last time. :P

**Comment by dusterio** [comment]
Not sure about 'Dusteri' either ;) But DOMDocument is shipped with any PHP 5+:
http://php.net/manual/en/class.domdocument.php

Is there a possibility that you have a lower version of PHP or dom/xml extension is not installed?

In Ubuntu Linux it's apt-get install php7.0-xml (or php5.5-xml for PHP 5.5)

**Comment by 33mhz** [comment]
Ah yes. Hm. Running php7.0, and php7.0-xml is installed. Interesting. But it looks like it was just another dependency not being up to date. My mistake!
